server:
  port: 9001

ribbon:
  eureka:
    enabled: false


zuul:
  routes:
    AOOMS:
      path: /get/**
      serviceId: test
      stripPrefix: false  # 保留代理前缀

test:
  ribbon:
    listOfServers: 127.0.0.1:9000